version: '3'

services:
  web:
    container_name: myriad-federated
    image: myriadsocial/myriad-federated
    build:
      context: ../../
      dockerfile: .maintain/docker/Dockerfile
    # env_file:
    #   - ../../.env
    ports:
      - 8080:80
    networks:
      myriad:
        ipv4_address: 172.27.1.6
        aliases:
          - myriad-federated

networks:
  myriad:
    external: true
